# Generated by Django 3.1.7 on 2021-03-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0002_auto_20210315_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='workout_time',
            field=models.PositiveSmallIntegerField(verbose_name='Продолжительность тренировки (минут)'),
        ),
    ]
